/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "B_LED.h"
#include "B_LED_aliases.h"
#include "SW.h"
#include "SW_aliases.h"
#include "G_LED.h"
#include "G_LED_aliases.h"
#include "R_LED.h"
#include "R_LED_aliases.h"
#include "EEPROM.h"
#include "timer_clock.h"
#include "timer_1_isr.h"
#include "Timer_1.h"
#include "UART_2.h"
#include "UART_2_SPI_UART.h"
#include "UART_2_PINS.h"
#include "UART_2_SPI_UART_PVT.h"
#include "UART_2_PVT.h"
#include "UART_2_BOOT.h"
#include "RE.h"
#include "RE_aliases.h"
#include "UART_2_SCBCLK.h"
#include "UART_2_tx.h"
#include "UART_2_tx_aliases.h"
#include "UART_2_SCB_IRQ.h"
#include "UART_2_rx.h"
#include "UART_2_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

